### PR TITLE
Added a second victorian-style template

### PR DESCRIPTION
**Pull request by stevecooperorg**
The new one is based on The Key Of Solomon;

     https://ia801308.us.archive.org/15/items/b24884431/b24884431.pdf

And he 'Eldritch' one has been made to look more like The Book of Black Magic and Pacts;

     https://ia803006.us.archive.org/22/items/BookOfBlackMagicWaite/Book%20of%20Black%20Magic%20-%20Waite.pdf

### CODE REVIEW

**Comment by ghost** [comment]
@stevecooperorg Merge conflict! I'll let you sort those out…

**Review by ghost — APPROVED** [review]

**Comment by kierun** [comment]
Urgh, wrong account… Again.

**Review by kierun — DISMISSED** [review]

**Comment by stevecooperorg** [comment]
ok, the merge conflict is fixed, but I had a terrible time with python and venvs and pipx and pre-commit and a broken symbolic link to a python interpreter on my mac. (God, I hate python's many ways to fail to install itself.) 

Upshot is I had to commit by removing the git commit hooks, so the rules might not be followed. It's a fairly straightfoward merge commit with the standard message so, ... hashtag shrug emoji.

**Review by kierun — APPROVED** [review]
LGTM

**Pull request merged**
